### ISSUE TITLE
Automatically detect latest Javacord version

### ISSUE THREAD

**Issue by Saladoc** [Javacord/Javacord-Bot#20]
The maven and gradle commands should not be limited to the version the bot is currently running on. They should fetch and display the latest release version, no matter which version of javacord powers the bot.

**Comment by Saladoc** [comment]
Also use this version in the `!maven` and `!gradle` commands.

**Comment by Bastian** [comment]
Can we prioritize this?
The latest version can be received from `https://docs.javacord.org/rest/latest-version/release`
