### ISSUE TITLE
Implement a !timeout command

### ISSUE THREAD

**Issue by Saladoc** [Javacord/Javacord-Bot#28]
Create a command `!timeout <user> <time>` that temporarily mutes a user.

A muted user can not post messages or reactions and is unable to join voice channels. If they were in a voice channel when being muted, they are also moved to the server's AFK channel if possible.

The command is available to the Maintainer group (id `151325992038825984`) in an unlimited form and to the contributor group (id: `399530229732868096`) in a form that is limited as follows
 - can be used a maximum of X times over a 24 hour period by the same person
 - will mute the target for a maximum duration of Y

After the time elapses a muted person is automatically unmuted. Subsequent calls for the same target will overwrite their timeout duration. A duration of zero or smaller acts as an unmute. 

All mute / unmute operations are to be logged to a channel specified by ID.

**Comment by Bastian** [comment]
I don't think we will need this.
If someone violates the rules I will want him. If this doesn't help, the user will be banned.

**Comment by Saladoc** [comment]
I agree, we can reconsider if the user load grows (or your time to monitor the server diminishes).
